absys/apps/abrechnung/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.RechnungSozialamtFormView.as_view(),
        name='abrechnung_rechnungsozialamt_form'
    ),
    url(
        r'^erfassungbekleidungsgeld/$',
        views.ErfassungBekleidungsgeldFormView.as_view(),
        name='abrechnung_erfassung_bekleidungsgeld_form'
    ),
    url(
        r'^(?P<pk>[\d]+)/pdf/',
        views.AbrechnungPDFView.as_view(),
        name='abrechnung_rechnungsozialamt_pdf'
    ),
    url(
        r'^(?P<pk>[\d]+)/bearbeiten/',
        views.RechnungSozialamtUpdateView.as_view(),
        name='abrechnung_rechnungsozialamt_update'
    ),
    url(
        r'^(?P<pk>[\d]+)/loeschen/',
        views.RechnungSozialamtDeleteView.as_view(),
        name='abrechnung_rechnungsozialamt_delete'
    ),
    url(
        r'^(?P<pk>[\d]+)/saxmbs/',
        views.SaxmbsView.as_view(),
        name='abrechnung_saxmbs_dat'
    ),
]

absys/config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    url(r'^passwort_aendern/$', auth_views.PasswordChangeView.as_view(), {'post_change_redirect': '/'},
        name='absys_passwort_aendern'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^anwesenheitsliste/', include('absys.apps.anwesenheitsliste.urls')),
    url(r'^abrechnung/', include('absys.apps.abrechnung.urls')),
    url(r'^benachrichtigungen/', include('absys.apps.benachrichtigungen.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(),
        {'template_name': 'anmeldung/templates/anmeldung/login.html'}, name='absys_login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(),
        {'next_page': reverse_lazy('dashboard_dashboard')}, name='absys_logout'),
    url(r'^', include('absys.apps.dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

absys/apps/abrechnung/models.py
from collections import deque, OrderedDict
import datetime
import decimal

import arrow
from django.db import models, router
from django.db.models.deletion import Collector
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from model_utils import Choices
from django.utils.functional import cached_property
from model_utils.models import TimeStampedModel


from absys.apps.einrichtungen.models import Einrichtung
from absys.apps.schueler.models import Schueler, Sozialamt

from . import managers


class RechnungSozialamt(TimeStampedModel):
    """
    Eine Sozialamtsrechnung fasst mehrere Rechnungen zusammen.

    - Sozialamt (Fremdschlüssel)
    - Sozialamt Anschrift
    - Startdatum
    - Enddatum
    
    ~M: Fasst die Rechnungen für die Kinder von Ganztagsbetreuung und Hp. Kita in Zeitraum zusammen
    """

    sozialamt = models.ForeignKey(Sozialamt, models.SET_NULL, null=True, verbose_name="Sozialamt",
        related_name='rechnungen')
    name_sozialamt = models.CharField(max_length=200)
    anschrift_sozialamt = models.TextField()
    startdatum = models.DateField("Startdatum")
    enddatum = models.DateField(
        "Enddatum",
        help_text=("Das Enddatum muss nach dem Startdatum liegen, "
            "darf aber nicht nach dem heutigen Datum liegen."
            " Außerdem müssen Startdatum und Enddatum im gleichen Jahr liegen.")
    )

    objects = managers.RechnungSozialamtManager.from_queryset(managers.RechnungSozialamtQuerySet)()

    class Meta:
        ordering = ('-startdatum', '-enddatum', 'sozialamt')
        unique_together = ('sozialamt', 'startdatum', 'enddatum')
        verbose_name = "Sozialamtsrechnung"
        verbose_name_plural = "Sozialamtsrechnungen"

    def __str__(self):
        msg = "Sozialamtsrechnung {s.nummer} für {s.sozialamt} ({s.startdatum} - {s.enddatum})"
        return msg.format(s=self)

    def save(self, *args, **kwargs):
        if self.sozialamt:
            if not self.name_sozialamt:
                self.name_sozialamt = self.sozialamt.name
            if not self.anschrift_sozialamt:
                self.anschrift_sozialamt = self.sozialamt.anschrift
        super().save(*args, **kwargs)

    def delete(self, using=None, keep_parents=False):
        """
        Löscht diese Instanz sowie alle nachfolgenden.

        Gelöscht werden alle :model:`abrechnung.RechnungSozialamt`-Instanzen,
        die zwischen dem `startdatum` dieser Rechnung und dem 31.12. im Jahr
        von `startdatum` liegen - unabhängig vom zugehörigen Sozialamt.
        """
        using = using or router.db_for_write(self.__class__, instance=self)
        assert self._get_pk_val() is not None, (
            "%s object can't be deleted because its %s attribute is set to None." %
            (self._meta.object_name, self._meta.pk.attname)
        )
        collector = Collector(using=using)
        collector.collect(
            RechnungSozialamt.objects.seit(self.startdatum),
            keep_parents=keep_parents
        )
        return collector.delete()

    delete.alters_data = True

    def clean(self):
        if self.startdatum > self.enddatum:
            raise ValidationError(
                {'enddatum': "Das Enddatum muss nach dem Startdatum liegen."},
                code='enddatum_nach_startdatum'
            )
        if self.enddatum > now().date():
            raise ValidationError(
                {'enddatum': "Das Enddatum darf nicht nach dem heutigen Datum liegen."},
                code='enddatum_nach_heute'
            )
        if self.startdatum.year != self.enddatum.year:
            raise ValidationError(
                {'enddatum': "Startdatum und Enddatum müssen im gleichen Jahr liegen."},
                code='enddatum_und_startdatum_nicht_im_gleichen_jahr'
            )
        qs = RechnungSozialamt.objects.filter(
            models.Q(
                models.Q(startdatum__range=(self.startdatum, self.enddatum)) |
                models.Q(enddatum__range=(self.startdatum, self.enddatum))
            ) |
            models.Q(startdatum__lte=self.startdatum, enddatum__gte=self.enddatum),
            sozialamt=self.sozialamt
        )
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        if qs.count():
            raise ValidationError(
                {'startdatum': "Für den ausgewählten Zeitraum existiert schon eine Rechnung."},
                code='startdatum_exitiert_schon'
            )
        qs = self.sozialamt.anmeldungen.zeitraum(self.startdatum, self.enddatum)
        for schueler_in_einrichtung in qs:
            einrichtung = schueler_in_einrichtung.einrichtung
            fehltage_immer_abrechnen = einrichtung.konfiguration.fehltage_immer_abrechnen
            bettengeldsaetze = einrichtung.bettengeldsaetze.zeitraum(
                self.startdatum, self.enddatum
            )
            if fehltage_immer_abrechnen and bettengeldsaetze.count() == 0:
                raise ValidationError(
                    ("Der Einrichtung {0} wurde für den Abrechnungszeitraum kein"
                        " Bettengeldsatz zugewiesen.").format(einrichtung),
                    code='einrichtung_ohne_bettengeld'
                )
            pflegesaetze = einrichtung.pflegesaetze.zeitraum(self.startdatum, self.enddatum)
            if pflegesaetze.count() == 0:
                raise ValidationError(
                    ("Der Einrichtung {0} wurde für den Abrechnungszeitraum kein"
                        " Pflegesatz zugewiesen.").format(einrichtung),
                    code='einrichtung_ohne_pflegesatz'
                )

    @property
    def nummer(self):
        return "S{:06d}".format(self.pk)

    def fehltage_abrechnen(self, schueler_in_einrichtung):
        """
        Nicht abgerechnete Rechnungspositionen pro Schüler seit Eintritt in die Einrichtung abrechnen.

        Args:
            schueler_in_einrichtung (SchuelerInEinrichtung): Instanz für die abgerechnet werden
                soll.

        Returns:
            list: Liste jener in diesem Ducrhgang abgerechneter Fehltage welche aus vorhergehenden
                Rechnungen stammen. D.h. 'nachträglich abgerechnete' Fehltage

        Note:
            Im Gegensatz zum 'generischen' ``fehltage_abrechnen`` ist diese Methode an einen
            konkreten Zeitraum 'gebunden'. Daraus ergibt sich das wir zwei verschiedene 'Sorten
            abgerechneter Fehltage' unterscheiden müssen:
                - Fehltage innerhalb des Rechnungszeitraums. Diese sind offensichtlich
                trivial als solche identifizierbar.
                - Fehltage aus vorhergehenden Rechnungen welche jedoch (aufgrund
                des Überschreitens des Grenzwertes) noch nicht abgerechnet wurden, jetzt aber
                bei *diesem* Rechnungslauf (weil ggf. erhöhter Schwellwert) abgerechnet wurden.
            Alte nicht abgerechnete Fehltage werden zwar problemlos von ``fehltage_abrechnen`` der
            Konfiguration abgerechnet, jedoch können sie danach nicht mehr von jenen Fehltagen
            unterschieden werden welche bereits in vorherigen Rechnungen abgerechnet wurden. Dies
            ist jedoch eine wesentliche Größe zur Berechnung der 'Zahltage'.
        """

        qs = RechnungsPositionSchueler.objects.nicht_abgerechnet(
            schueler_in_einrichtung, self.enddatum
        )
        abgerechnete_fehltage = schueler_in_einrichtung.einrichtung.konfiguration.fehltage_abrechnen(
            qs, schueler_in_einrichtung
        )
        nachtraeglich_abgerechnete_fehltage = []
        for position in abgerechnete_fehltage:
            if position.rechnung_sozialamt != self:
                nachtraeglich_abgerechnete_fehltage.append(position)
        return nachtraeglich_abgerechnete_fehltage

    @cached_property
    def mittelwert_kapitel(self):
        """
        Liefere den Mittelwert aller Kapitel.

        Da jede Schule nur ein Kapitel hat, ist der Mittelwert aller Kapitel im gleich dem
        gesetzten Kapitel.
        """
        return settings.ABSYS_SAX_KAPITEL

    def get_tage(self, block_groesse=31):
        """
        Liefere eine Liste der Tage (datetime.date) im Rechnungszeitraum.

        Args:
            block_groesse (int or None, optional): Teile die Liste der Tage in
                Teilblöcke der Grösse ``block_groesse`` auf. Default ist
                ``31``.

        Returns:
            list: Eine Liste von ``deque`` Instanzen. Jedes ``deque``
            beinhaltet maximal ``block_groesse`` viele ``datetime.date``s.
            Wenn ``block_groesse=None`` oder die Anzahl der
            Tage <= ``block_groesse`` hat diese Liste nur ein Element.
        """

        tage = arrow.Arrow.range(
            'day',
            arrow.get(self.startdatum),
            arrow.get(self.enddatum)
        )
        tage = [tag.date() for tag in tage]

        result = []
        if block_groesse is None:
            result.append(tage)
        else:
            while tage:
                zeitraum = deque()
                while ((len(zeitraum) < block_groesse) and tage):
                    zeitraum.append(tage.pop(0))
                result.append(zeitraum)
        return result

    def get_prefix_tage(self, length=3):
        """Liefere eine Liste von Daten die unmittelbar vor dem Rechnungsdatum liegen."""
        start = self.startdatum - datetime.timedelta(length)
        prefix = [start + datetime.timedelta(i) for i in range(length)]
        return prefix

    def get_suffix_tage(self, length=3):
        """Liefere eine Liste von Daten die unmittelbar nach dem Rechnungsdatum liegen."""
        end = self.enddatum
        suffix = [end + datetime.timedelta(i) for i in range(1, 1 + length)]
        return suffix


class RechnungsPositionSchueler(TimeStampedModel):
    """
    Daten einer Rechnungsposition für einen Schüler an einem bestimmten Datum.

absys/apps/abrechnung/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, HTML, Layout, Submit
from crispy_forms.bootstrap import FormActions
from django import forms

from absys.apps.schueler import models


class RechnungSozialamtForm(forms.Form):

    enddatum = forms.DateField(
        label="Enddatum",
        help_text=(
            "Das Enddatum muss nach dem Startdatum liegen, "
            "darf aber nicht nach dem heutigen Datum liegen."
            " Außerdem müssen Startdatum und Enddatum im gleichen Jahr liegen.")
    )
    sozialaemter = forms.ModelMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Wir weisen das queryset in __init__ zu um sicherzugehen das es bei
        # jeder Formgenerierung neu evaluiert wird.
        self.fields['sozialaemter'].queryset = models.Sozialamt.objects.order_by('name')

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div(
                    HTML("<p><strong>Das Startdatum wird für jedes Sozialamt automatisch ermittelt.</strong></p>"),
                    Div(
                        HTML(
                            "Existiert schon eine Rechnung für das Sozialamt, ist das Startdatum der Tag nach dem Enddatum der letzten Rechnung. Ansonsten ist es der 1. Januar des Jahres, das im Enddatum angegeben ist."
                        ),
                        css_class='help-block'
                    ),
                    css_class='col-md-4'
                ),
                Div(
                    Field('enddatum'),
                    css_class='col-md-4'
                ),
                Div(
                    Field('sozialaemter'),
                    css_class='col-md-4'
                ),
                css_class="row"
            ),
            FormActions(
                Submit('submit', "Rechnungen erstellen", css_class="btn btn-success")
            )
        )


class ErfassungBekleidungsgeldForm(forms.Form):

    schueler_in_einrichtung_id = forms.IntegerField(widget=forms.HiddenInput())
    schueler = forms.CharField(label="", required=False)
    einrichtung = forms.CharField(label="", required=False)
    bekleidungsgeld = forms.DecimalField(label="", max_digits=5, decimal_places=2)


class ErfassungBekleidungsgeldFormHelper(FormHelper):

    def __init__(self, has_initial, *args, **kwargs):
        super().__init__(*args, **kwargs)
        submit_label = "Bekleidungsgeld erfassen"
        if not has_initial:
            submit_label = "Rechnungen erstellen"
        self.add_input(Submit('submit', submit_label, css_class="btn btn-success"))
        self.layout = Layout(
            Div(
                Div(
                    Field('schueler',  disabled=''),
                    css_class='col-md-5 dark'
                ),
                Div(
                    Field('einrichtung',  disabled=''),
                    css_class='col-md-5 dark'
                ),
                Div(
                    Field('bekleidungsgeld'),
                    Div(HTML("€"), css_class="input-group-addon"),
                    css_class='col-md-2 input-group'
                ),
                css_class="row"
            ),
        )


class RechnungSozialamtUpdateFormHelper(FormHelper):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_tag = False
        self.render_hidden_fields = True #sicherheitshalber falls es wie Unten nicht geht
        self.layout = Layout(
            Div(
                Div(
                    Field('name_sozialamt'),
                    css_class='col-md-6'
                ),
                Div(
                    Field('anschrift_sozialamt', rows=5),
                    css_class='col-md-6'
                ),
                css_class="row"
            ),
        )


class RechnungEinrichtungUpdateFormHelper(FormHelper):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_tag = False
        self.render_hidden_fields = True #Fix für "Update des BKZ geht nicht" -> weil die ID (also die Hidden Fiels) nicht an die Crispy Form durchgereicht werden und django die inline form dann nichtmehr zuordnen kann.
        self.layout = Layout(
            Div(
                Div(
                    Field('buchungskennzeichen'),
                    css_class='col-md-6'
                ),
                Div(
                    Field('datum_faellig'),
                    css_class='col-md-6'
                ),
                css_class="row"
            ),
        )

absys/apps/abrechnung/templates/abrechnung/erfassung_bekleidungsgeld.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Bekleidungsgeld erfassen{% endblock title %}

{% block content %}
  <h3>
    Bekleidungsgeld erfassen<br>
    <small>{{ view.startdatum }} bis {{ view.enddatum }}</small>
  </h3>
  {% if not view.initial %}
    <p>Es sind keine Bekleidungsgelder zu erfassen.</p>
  {% endif %}
  {% crispy formset view.helper %}
{% endblock content %}

absys/apps/abrechnung/templates/abrechnung/pdf.html
{% load static %}
<head>
    <meta charset="utf-8">
    <title>AbSys</title>
    <meta name="description" content="Abrechnungssystem der SLSH und LZH.">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/bootstrap-theme.min.css"%}">
    <link rel="stylesheet" href="{% static "/css/main.css" %}">
</head>
<body>
<div id="page-1">
  <h1>Rechnung</h1>
  <div id="address">
    <div id="von">
      <p>{{ view.adresse_schule|linebreaks }}</p>
    </div>
    <div id="an">
      <p>{{ rechnungsozialamt.anschrift_sozialamt|linebreaks }}</p>
    </div>
  </div>
  <div id="details">
    <p><strong>Rechnungsnummer:</strong>{{ rechnungsozialamt.nummer }}<br>
    {% if rechnungsozialamt.sozialamt.sbkz %}
      <strong>BKZ des Sozialamts:</strong>{{ rechnungsozialamt.sozialamt.sbkz }}<br>
    {% endif %}
    <strong>Abrechnungszeitraum:</strong>
    {{ rechnungsozialamt.startdatum|date:"SHORT_DATE_FORMAT" }}
    -
    {{ rechnungsozialamt.enddatum|date:"SHORT_DATE_FORMAT" }}</p>
    <p><strong>Einrichtungen zur Abrechnung:</strong><br>
      {% for einrichtungsrechnung in rechnungsozialamt.rechnungen_einrichtungen.all %}
        {{ einrichtungsrechnung.name_einrichtung }}{% if not forloop.last %},{% endif %}
      {% endfor %}
    </p>
  </div>
</div>

{# Einrichtungsrechnungen #}
{% for einrichtungsrechnung in rechnungsozialamt.rechnungen_einrichtungen.all %}
<div {% if forloop.first %}id="page-2"{% else %}class="page-subsequent">{% endif %}
  {% include 'abrechnung/pdf/_einrichtungsrechnung.html' %}
</div>
{% endfor %}

{# Footer #}
<br><br><br><br>
<hr>
<h3> <center> ENDE DER SOZIALAMTRECHNUNG {{ rechnungsozialamt.nummer }}
  FÜR DEN ZEITRAUM VOM {{ rechnungsozialamt.startdatum|date:"SHORT_DATE_FORMAT" }}
  BIS {{ rechnungsozialamt.enddatum|date:"SHORT_DATE_FORMAT" }} </center></h3>
</body>

absys/apps/abrechnung/templates/abrechnung/rechnung_sozialamt_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Rechnungen{% endblock title %}

{% block content %}
  <h3>Rechnungen</h3>
  {% crispy form %}
  <table class="table table-striped">
    <thead>
       <tr>
        <th>Startdatum</th>
        <th>Enddatum</th>
        <th>Sozialamt</th>
        <th>Nummer</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for rechnung in object_list|dictsortreversed:"nummer" %}
        <tr>
          <td>{{ rechnung.startdatum|date:"SHORT_DATE_FORMAT" }}</td>
          <td>{{ rechnung.enddatum|date:"SHORT_DATE_FORMAT" }}</td>
          <td>{{ rechnung.name_sozialamt }}</td>
          <td>{{ rechnung.nummer }}</td>
          <td class="rechnung-buttons">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span> Downloads
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'abrechnung_rechnungsozialamt_pdf' pk=rechnung.pk %}">PDF</a>
                </li>
                <li>
                  <a href="{% url 'abrechnung_saxmbs_dat' pk=rechnung.pk %}">SAXMBS</a>
                </li>
              </ul>
            </div>

            {% if perms.abrechnung.change_rechnungsozialamt %}
            <a href="{% url 'abrechnung_rechnungsozialamt_update' pk=rechnung.pk %}" class="btn btn-primary btn-xs">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Bearbeiten
            </a>
            {% endif %}
            {% if  perms.abrechnung.delete_rechnungsozialamt %}
            <a href="{% url 'abrechnung_rechnungsozialamt_delete' pk=rechnung.pk %}" class="btn btn-danger btn-xs">
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Löschen
            </a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

absys/apps/abrechnung/templates/abrechnung/rechnungsozialamt_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Rechnung {{ rechnungsozialamt.nummer }} für {{ rechnungsozialamt.sozialamt }} löschen
{% endblock title %}

{% block content %}
  <h3>
    Rechnung {{ rechnungsozialamt.nummer }} für {{ rechnungsozialamt.sozialamt }} löschen<br>
    <small>{{ rechnungsozialamt.startdatum|date:"SHORT_DATE_FORMAT" }} - {{ rechnungsozialamt.enddatum|date:"SHORT_DATE_FORMAT" }}</small>
  </h3>
  <form action="" method="post">
    {% csrf_token %}
    <p>Sind Sie sicher, dass Sie die folgenden Rechnungen löschen möchten?</p>
    {% for rechnung_sozialamt in view.kandidaten %}
      <li>Rechnung {{ rechnung_sozialamt.nummer }} für {{ rechnung_sozialamt.sozialamt }} vom {{ rechnung_sozialamt.startdatum|date:"SHORT_DATE_FORMAT" }} - {{ rechnung_sozialamt.enddatum|date:"SHORT_DATE_FORMAT" }}</li>
      <ul>
        {% for rechnung_einrichtung in rechnung_sozialamt.rechnungen_einrichtungen.all %}
          <li>Einrichtungs-Rechnung {{ rechnung_einrichtung.nummer }} für Einrichtung {{ rechnung_einrichtung.name_einrichtung }}</li>
        {% endfor %}
      </ul>
    {% endfor %}
    </ul>
    <div class="form-actions">
        <input type="submit" name="delete" value="Löschen" class="btn btn-danger" id="submit-delete">
        <a class="btn btn-default" href="{% url 'abrechnung_rechnungsozialamt_form' %}">Abbrechen</a>
    </div>
  </form>
{% endblock content %}

absys/apps/abrechnung/templates/abrechnung/rechnungsozialamt_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Rechnung {{ rechnungsozialamt.nummer }} bearbeiten
{% endblock title %}

{% block content %}
  <h3>
    Rechnung {{ rechnungsozialamt.nummer }} bearbeiten<br>
    <small>{{ rechnungsozialamt.startdatum }} - {{ rechnungsozialamt.enddatum }}</small>
  </h3>
  <form action="{% url 'abrechnung_rechnungsozialamt_update' pk=rechnungsozialamt.pk %}" method="post">
    {% crispy form view.helper_sozialamt %}
    {{ inlines.0.management_form }}
    {% for inline in inlines.0 %}
      <h4>Einrichtungs-Rechnung {{ inline.instance.nummer }} für Einrichtung {{ inline.instance.name_einrichtung }}</h4>
      {% crispy inline view.helper_einrichtung %}
    {% endfor %}
    <div class="form-actions">
        <input type="submit" name="submit" value="Speichern" class="btn btn-success" id="submit-save">
        <a class="btn btn-default" href="{% url 'abrechnung_rechnungsozialamt_form' %}">Abbrechen</a>
    </div>
  </form>
{% endblock content %}